### ISSUE TITLE
roadmap

### ISSUE THREAD

**Issue by JerryBian** [JerryBian/dff#2]
A list of potential supported features.

- [x] Performance improvement: Group by File Size and do full iteration only Once.
- [ ] Output to specified folder
- [ ] Cancellation support
   - It should print processed results
- [x] Support to export all duplicated path to external file
